
* 中国石油大学(华东)本科毕业设计论文LaTeX模板2020

这个项目是中国石油大学(华东)2020本科毕业设计论文word模板的LaTex版。



本项目的目的在于让同学们在写毕业论文时能够专注于论文内容的编写，而非细枝末节的排版问题，从而节省下许多不必要的工作量。

当然，如果你之前从未使用过LaTex，你会需要一些时间来了解这个工具和配置工作环境。

使用此模板的过程中，比较简单的问题可以在qq群1105166609中互助解决。如果模板中出现错误，或者模板缺乏你需要的功能，请在[[https://github.com/walkman-z/upc-thesis-2020/
issues][walkman-z/upc-thesis-2020]]上提交issue。

如果我的工作节省了你的工作量和时间，请向你的同学，老师，以及学弟学妹们推荐此模板。


** 为什么使用LaTex写论文？


Latex的优点在于 
+ 跨平台、免费、开源
+ 稳定、精确、美观
+ 易用、全面的数学排版支持。
+ 让你专注于内容的写作



** 工具链

LaTex的源文件是一系列纯文本文件，你可以在你喜欢的任何文本编辑器中编写你的源文件。主流的文本编辑器都对LaTeX有着完善丰富的插件支持。

常见的Latex工作环境有

+ texworks 安装texlive时自带。
+ sublimetext3 简单易用，比较推荐。
+ VScode 没试过，似乎功能很丰富。
+ atom 没试过。
+ emacs 古老的编辑器，很难上手，但配置好后效率极高。
+ vim 同上。


要高效率的使用latex写论文，以下几个功能我认为是不可或缺的

+ 命令高亮
+ 快速插入环境、公式等
+ 关键字补全
+ 实时的公式显示
+ tex文件和pdf文件的正、反向搜索
+ 快速的搜索\替换功能


这里推荐大家使用sublimetext3加插件配合sumatra PDF阅读器的方式。
需要的插件有
+ LaTeXtools
+ LaTeXXYZ
+ LaTeX-cwl
在网上搜索"sublimtext3 latex"就可以找到许多配置教程。在这里就不赘述了。

一些写论文时可能会用到的网站和工具：

如果你不想记大量的LaTeX数学命令，或者你有一些又臭又长的公式，你可以在网站[[https://www.latexlive.com/][latexlive]]上以类似word的公式编辑器一样的方式。这个网站还具有许多其他功能，如将公式输出为图片，输出公式到Word，手写公式识别，图片公式识别（写文献翻译必备）等。

知网英文版
知网上下载文献很多时候只能下载caj格式，但如果你设置知网语言为英文，就可以直接下载文献的PDF版。

另外，基本上百分之九十的英文文献都可以在scihub上免费下载，请自行搜索网址和使用方法。



** 模板使用指南
请参见主文件中的内容

** 工作内容
*** 已解决的问题
+ 修正附录的目录的不正常缩进
+ 较长论文题目的换行首字对齐
+ 较长中英关键字的换行首字对齐
+ 加入定理类环境
+ 加入双面打印宏，取消注释后自动在特定位置添加空白页

*** 解决中的问题
+ 将模板拆分结构化，实现单章的独立编译
+ 分离导言区的设置
+ 将双面打印功能直接整合进环境中
+ 完善REEADME

*** 拟解决的问题
+ 各种代码类环境的实现
+ 考虑使用纯英文写毕业论文的兼容性
+ 暂时设置为手动引用参考文献，未来将实现bib引用参考文献的样式


** 模板历史及感谢

本模板的主要代码来自于[[https://github.com/DotWang/UPCThesis_advanced/commits/master][DotWang/UPCThesis_advanced]]。
